var car = "corolla";
console.log("Is car == 'corolla'? I predict True.");
console.log(car == "corolla");
var fruit = "apple";
console.log("Is fruit == 'mango'? I predict False.");
console.log(fruit == 'mango');
var number = "8";
console.log("Is number == '8'? I predict True.");
console.log(number == '8');
var mobile = "iphone 14 pro max";
console.log("Is mobile == 'iphone 13 pro max'? I predict False.");
console.log(mobile == 'iphone 13 pro max');
var weather = "rainy";
console.log("Is weather == `rainy` ? I predict True. ");
console.log(weather == 'rainy');
var animal = "cat";
console.log("Is animal ==`lion` ? I predict False. ");
console.log(animal == 'lion');
var food = "biryani";
console.log("Is food == `biryani` ? I predict True.");
console.log(food == "biryani");
var employee = "ali";
console.log("Is employee == `akram` ? I predict False. ");
console.log(employee == "akram");
var colour = "red";
console.log("Is colour == `red` ? I predict True. ");
console.log(colour == "red");
var course = "AI";
console.log("Is course == `Metaverse` ? I predict False. ");
console.log(course == "Metaverse");
